name: Backend

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:11
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: flarum_test

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: curl, dom, gd, json, mbstring, openssl, pdo_mysql, tokenizer, zip
          tools: phpunit, composer:v2

      - name: Create MySQL database
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS flarum_test;"
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root'; FLUSH PRIVILEGES;"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup tests
        run: composer test:setup
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: flarum_test
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_PREFIX: ""
          FLARUM_TEST_TMP_DIR_LOCAL: tests/integration/tmp

      - name: Run tests
        run: composer test
